[package]
authors = ["Henri Lunnikivi <heggggxa@gmail.com>"]
edition = "2018"
name = "spp-experiments"
version = "0.1.0"

[dependencies]
criterion = "0.3.4"
float-ord = "0.2.0"
rand = "0.8.3"

[[bench]]
harness = false
name = "bench"
